# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1505211720);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1505211840);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1505293364);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1505211600);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1505293244);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150125222008");
user_pref("browser.slowStartup.averageTime", 13157);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150125222008");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1505297639593");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1505211306912");
user_pref("datareporting.policy.firstRunTime", "1505211239593");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 6251);
user_pref("datareporting.sessions.current.main", 1060);
user_pref("datareporting.sessions.current.sessionRestored", 6753);
user_pref("datareporting.sessions.current.startTime", "1505293832329");
user_pref("datareporting.sessions.current.totalTime", 32);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1505211235733,\"a\":1,\"t\":1030,\"c\":true,\"m\":1291,\"fp\":10503,\"sr\":11103}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1505212325242,\"a\":1,\"t\":4,\"c\":true,\"m\":40,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1505219046096,\"a\":3,\"t\":32,\"c\":false,\"m\":1033,\"fp\":5228,\"sr\":6310}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1505289521033,\"a\":109,\"t\":3974,\"c\":true,\"m\":845,\"fp\":6089,\"sr\":6389}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1505293496321,\"a\":17,\"t\":181,\"c\":true,\"m\":20,\"fp\":901,\"sr\":1038}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"35.0.1\",\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"35.0.1\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"35.0.1\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1505211721);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1424288155000,\"mt\":1422226960000},\"langpack-pl@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-pl@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"55.0.2\",\"st\":1502931315000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"55.0.2\",\"st\":1502931036000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"55.0.2\",\"st\":1502931036000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424288210000,\"mt\":1420839872000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1424288211000,\"mt\":1407283796000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1424288211000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1424288211000,\"mt\":1390969548000}}}");
user_pref("gecko.buildID", "20150125222008");
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1505211426);
user_pref("loop.soft_start_ticket_number", 3540290);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1505211313);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1505211312);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1505211426);
user_pref("places.history.expiration.transient_current_max_pages", 100660);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("spellchecker.dictionary", "en_ZA");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1505211426);
user_pref("toolkit.startup.last_success", 1505293833);
user_pref("toolkit.telemetry.previousBuildID", "20150125222008");
